theme: jekyll-theme-minimal
title: JFKReveal
description: AI Analysis of JFK Assassination Documents
show_downloads: true
google_analytics: 
github:
  repository_url: https://github.com/PimpMyNines/JFKReveal