remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
title: JFKReveal
description: AI Analysis of JFK Assassination Documents
show_downloads: true
github:
  zip_url: https://github.com/PimpMyNines/JFKReveal/archive/refs/heads/main.zip
  tar_url: https://github.com/PimpMyNines/JFKReveal/archive/refs/heads/main.tar.gz
  repository_url: https://github.com/PimpMyNines/JFKReveal