name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      OPENAI_EMBEDDING_MODEL: "text-embedding-3-large"
      OPENAI_ANALYSIS_MODEL: "gpt-3.5-turbo"
      USE_MOCK_API: ${{ secrets.OPENAI_API_KEY == '' && '1' || '0' }}

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: pip
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov
        pip install -e .
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y tesseract-ocr
        
    - name: Run unit tests
      run: |
        pytest tests/unit/ -v
        
    - name: Run integration tests
      run: |
        pytest tests/integration/ -v
        
    - name: Run E2E tests on main branch with mocks
      if: github.ref == 'refs/heads/main'
      run: |
        # Run E2E tests with mock API if no OpenAI API key is available
        # or with real API if key is available but in safe controlled mode
        if [ "$USE_MOCK_API" = "1" ]; then
          echo "Running E2E tests with mock API"
          RUN_E2E_IN_CI=1 pytest tests/e2e/ -v
        else
          echo "Running E2E tests with real API but skipping full tests"
          RUN_E2E_IN_CI=1 pytest tests/e2e/ -v --skip-mark="skipif_api_required"
        fi
    
    - name: Summarize test coverage
      run: |
        pytest --cov=src/jfkreveal/ --cov-report=term-missing